### ISSUE TITLE
Workflows Failing

### ISSUE THREAD

**Issue by nickrodgers42** [awslabs/smithy-language-server#97] opened 2023-04-14 22:59 UTC
I was trying to build the language server using the `.gradlew` file and noticed that it was failing on my machine (WSL 2 using Ubuntu). Given that it's a weird platform I tried on my Macbook, same failures. I forked the repo and ran the workflows on the tip of `main`, only changing the .README file, same failures. 

https://github.com/nickrodgers42/smithy-language-server/actions/runs/4704512621/jobs/8344210410

**Comment by srchase** [comment] 2023-04-14 23:24
This looks like it started with the release of Smithy `1.30.0`.

If I pin the Smithy version to `1.29.0` in build.gradle ([here](https://github.com/awslabs/smithy-language-server/blob/main/build.gradle#L160), the running `./gradlew clean build` succeeds.

I need look into what specific change in `1.30.0` is causing this issue on the Language Server.

Due to the `definitionLocationsV2` test failing, it's likely the cause of https://github.com/awslabs/smithy-language-server/issues/96.

**Comment by srchase** [comment] 2023-04-19 13:59
Resolved in #98.

**Closed by srchase** 2023-04-19 13:59 UTC
Labels: bug
